<?php

namespace AppBundle\Repository;

/**
 * GameGroupVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameGroupVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
