<?php

namespace AppBundle\Repository;

/**
 * GameGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
