<?php

namespace AppBundle\Repository;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumLikesPost($post) {
        return $query = $this->getEntityManager()
            ->createQuery(
                'SELECT count(l.id) FROM AppBundle:PostLike l WHERE l.post = :post'
            )->setParameter('post', $post)
            ->getSingleScalarResult()
        ;
    }

    public function getUserHasLikePost($post, $user) {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT count(l.id) FROM AppBundle:PostLike l WHERE l.post = :post AND l.user = :user'
            )->setParameters(array('post' => $post, 'user' => $user))
            ->getSingleScalarResult();
        
        if($query == 1) return 'liked';
        else return 'unliked';
    }

    public function getNumPostUserHasLiked($user) {
        return $query = $this->getEntityManager()
            ->createQuery(
                'SELECT count(l.id) FROM AppBundle:PostLike l WHERE l.user = :user'
            )->setParameter('user', $user)
            ->getSingleScalarResult();
    }
}
