<?php

namespace AppBundle\Repository;

/**
 * TournamentPairingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentPairingRepository extends \Doctrine\ORM\EntityRepository
{
}
