<?php

namespace AppBundle\Repository;

/**
 * TournamentRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRuleRepository extends \Doctrine\ORM\EntityRepository
{
}
