<?php

namespace AppBundle\Repository;

/**
 * tournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tournamentRepository extends \Doctrine\ORM\EntityRepository
{
}
