<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByUsername($username) {
        $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT u FROM AppBundle:user u WHERE u.username LIKE :username'
                )->setParameter('username', '%'.$username.'%');
        
        return $query->getResult();
    }
}
